sliced_data_folder_clean: /root/EasyCog/data/data_v0428/sliced_feat_train/asreog_filter_order3_clean_data_0426
sliced_trials_json_clean: /root/EasyCog/data_json_files/proc_compare_json/converted_asreog_filter_order3_clean_data_0426.json

sliced_data_folder_all: /root/EasyCog/data/data_v0428/sliced_feat_train/asreog_filter_order3_all_data
sliced_trials_json_all: /root/EasyCog/data_json_files/proc_compare_json/converted_asreog_filter_order3_all_data_0426.json

dataloader: EasyCog_Dataloader

cog_task: 'resting' # 'video' or 'resting' or 'all'

input_type_list:
- EEG


input_format_dict:
  EEG:
  - sequence


gt_type_list:
- Task_id ### loss will neglect this due to only resting task
# - Subject_id
- Subject_Category
- MoCA_Task_Score
- MMSE_Task_Score

gt_format_dict:
  Task_id:
  - value
  Subject_Category:
  - value
  MoCA_Task_Score:
  - value
  MMSE_Task_Score:
  - value

norm_params:
  EEG:
    sequence:
      max_value: 8087.9805
      mean_value: -0.0003434395
      min_value: -7018.4287
      norm_type: norm_by_subject_task
      std_value: 20.800686
  # Forehead_EEG:
  #   sequence:
  #     max_value: 
  #     mean_value: 
  #     min_value: 
  #     norm_type: norm_by_mean_std
  #     std_value: 
  EOG:
    sequence:
      max_value: 1965.036519799067
      mean_value: -0.0045129696270988975
      min_value: -1584.1758942682995
      norm_type: norm_by_mean_std
      std_value: 14.824471300284605
  Gaze_posi:
    sequence:
      max_value: 3200.46688992919
      mean_value: 972.4825660968037
      min_value: -409.99182789123677
      norm_type: norm_by_mean_std
      std_value: 393.044501894086
  MMSE:
    value:
      max_value: 30.0
      mean_value: 23.033305227655987
      min_value: 7.0
      norm_type: norm_by_min_max
      std_value: 5.717059718000392
  MoCA:
    value:
      max_value: 28.0
      mean_value: 17.8941496951615
      min_value: 3.0
      norm_type: norm_by_min_max
      std_value: 6.793486787029787
  MoCA_Task_Score:
    value:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  MMSE_Task_Score:
    value:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  Subject_Category:
    value:
      norm_type: no_norm
  Subject_id:
    value:
      norm_type: no_norm
  Task_id:
    value:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  Task_embed:
    last_token:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  Task_score:
    value:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  STFT:
    sequence:
      max_value: 42849.39025707162
      mean_value: 2.7748861861441707
      min_value: 7.812917225790438e-15
      norm_type: norm_by_mean_std
      std_value: 34.63873977878058
  PCA:
    sequence:
      max_value: 7946591653.57875
      mean_value: 2.6594581542754934e-07
      min_value: -25072280535.421627
      norm_type: norm_by_mean_std
      std_value: 918031031.5517336
  Raw_feat:
    sequence:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~


data_aug_methods:
  train:
    EEG:
      pink_noise:
        aug_times: 1
        amplitude: 0.3
      # # random_mask:
      # #   aug_times: 2
      # #   mask_ratio: 0.5
      # no_aug:
      #   aug_times: 1
      # random_region_re_reference:
      #   aug_times: 1
      # random_mask_sequence:
      #   aug_times: 2
      #   mask_ratio: 0.5
    Subject_Category:
      no_aug:
        aug_times: 1
    Subject_id:
      no_aug:
        aug_times: 1
    Task_id:
      no_aug:
        aug_times: 1
    Task_embed:
      no_aug:
        aug_times: 1
    MoCA:
      no_aug:
        aug_times: 1
    MMSE:
      no_aug:
        aug_times: 1
    MoCA_Task_Score:
      no_aug:
        aug_times: 1
    MMSE_Task_Score:
      no_aug:
        aug_times: 1
  test:
    EEG:
      no_aug:
        aug_times: 1
    Subject_id:
      no_aug:
        aug_times: 1
    Task_id:
      no_aug:
        aug_times: 1
    Task_embed:
      no_aug:
        aug_times: 1
    MoCA:
      no_aug:
        aug_times: 1
    MMSE:
      no_aug:
        aug_times: 1
    MoCA_Task_Score:
      no_aug:
        aug_times: 1
    MMSE_Task_Score:
      no_aug:
        aug_times: 1

num_workers: 2
persistent_workers: True
prefetch_factor: 2

model:
  name: Joint_CLS_REG_Model
  cls_model_name: CBraMod_BaseModel
  reg_model_name: Regression_Transformer_TaskScore # Regression_Transformer
  contrast_method: sample
  reg_return_features: ~
  input_channels: 16
  emb_size: 40
  cls_emb_size: 40 ### for the cls model
  num_classes: 1
  load_pretrained_backbone: True ### load pretrained backbone for resting task
  freeze_backbone: True ### freeze the backbone for resting task
  freeze_cls_model: False ### do not freeze the last layer of the cls model for resting task
  cls_n_dim: 200
  cls_depth: 12
  backbone_weight_path: from utils.mask_pretrain_models_resting.py
  n_dim: 200
  reg_depth: 2
  num_reg_dims: 2
  reg_hidden_dims: [1024, 512, 256, 32]
  input_length: 375
  patch_sizes: [25, 16]
  vlm_fusion_type: ~
  pretrained: ~
  T: 0.07
  K: 8192
  m: 0.999
  aug_methods: ### same as the data_augs in the regressor cfg file
    features_preprocess:
        # method: task_preprocessing
        # contrast_task:
        #   - 2
        #   - 3
        #   - 6
        ### remove this for ablation on No Intra-task Attention
        method: intra_task_average
        # method: intra_task_attention ### task attention includes task_preprocessing
        contrast_task:
          - 2
          - 3
          - 6
    bias_aug: False
    train:
      features:
        # remove this for ablation on No Task Random Order
        # random_intra_task_sample-random_order_numpy_array: 
        #   aug_times: 100
        #   feat_len: 256
        #   sample_ratio: 0.6
        #   ratio: 1 
        # mix_up:
        #   aug_times: 100
        avg_intra_task_sample:
          aug_times: 1
          ratio: 1
      MMSE:
        no_aug:
          aug_times: 1
      MoCA:
        no_aug:
          aug_times: 1
      MMSE_taskscore:
        no_aug:
          aug_times: 1
      MoCA_taskscore:
        no_aug:
          aug_times: 1
    test:
      features:
        avg_intra_task_sample:
          aug_times: 1
          ratio: 1
      MMSE:
        no_aug:
          aug_times: 1
      MoCA:
        no_aug:
          aug_times: 1
      MMSE_taskscore:
        no_aug:
          aug_times: 1
      MoCA_taskscore:
        no_aug:
          aug_times: 1


Loss:
  name: CrossEntropy
  params:
    alpha: 1

  
Test_Loss:
  name: CrossEntropy
  params:
    alpha: 1


seed: 43
cpu: ~
cpu_affinity: ~
gpu: 1

batch_size: 64
lr_init: 0.001
warmup_epochs: 20 # 10
epochs: 100 # 50
scheduler: cosine
optimizer: Adam

cross_validation: 5-folder
train: True
evaluate: ~
resume: ~

train_stage: vanilla

DA:
  if_use: False
  Adapt_Data_Ratio: 1
  methods: ~

### This is for saving path. 
### You need to make sure you have the permission to write in this path.
save_path: /root/EasyCog/saved_models/checkpoints_Ablations/FrozenCLS_TrainableReg_RestingOnly
train_subject: ~
valid_subject: ~
test_subject: ~

is_split_trials_json_dict: True
logger_file: ~

record: record.txt
save_epoch: 10

### This is for single-task classification
classes: 10
task: classification

### This is for multi-task classification and regression
### If there is multi-task, please use this. The above single-task classification will be ignored.
### classificaton-10, classification-{num_classes} | regression-{num_dims}
### The first item is for classification, the second is for MoCA regression, the third is for MMSE regression
# multi-task: ~ # [classification-10, regression-1, regression-1] 
multi-task: [classification-1] 


### This is for printing and testing frequency
print_freq: 10
test_freq: 1

### This is for mask-autoencoder pretrain
### If there is no mask-autoencoder pretrain, please ignore this.
mask_ratio: 0.25

debug: False


pic_finetune: False