sliced_data_folder_clean: /mnt/glusterfs/home/zhenghang/hqy/EasyCog/data_v0428/sliced_feat_train/asreog_filter_order3_clean_data_0426
sliced_trials_json_clean: /home/zhenghang/qingyong/EasyCog/data_json_files/proc_compare_json/converted_asreog_filter_order3_clean_data_0426.json

sliced_data_folder_all: /mnt/glusterfs/home/zhenghang/hqy/EasyCog/data_v0428/sliced_feat_train/asreog_filter_order3_all_data
sliced_trials_json_all: /home/zhenghang/qingyong/EasyCog/data_json_files/proc_compare_json/converted_asreog_filter_order3_all_data_0426.json

dataloader: EasyCog_Dataloader

cog_task: 'video' # 'video' or 'resting' or 'all'

input_type_list:
- Gaze_posi

input_format_dict:
  Gaze_posi:
  - sequence

gt_type_list:
- Task_id
- MoCA_Task_Score
- MMSE_Task_Score

gt_format_dict:
  Task_id:
  - value
  MoCA:
  - value
  MMSE:
  - value
  MoCA_Task_Score:
  - value
  MMSE_Task_Score:
  - value

data_aug_methods:
  train:
    EEG:
      # pink_noise:
      #   aug_times: 1
      #   amplitude: 0.3
      # # random_mask:
      # #   aug_times: 2
      # #   mask_ratio: 0.5
      no_aug:
        aug_times: 1
      # random_region_re_reference:
      #   aug_times: 1
    Gaze_posi:
      no_aug:
        aug_times: 1
    Task_id:
      no_aug:
        aug_times: 1
    Task_embed:
      no_aug:
        aug_times: 1
    MoCA:
      no_aug:
        aug_times: 1
    MMSE:
      no_aug:
        aug_times: 1
    MoCA_Task_Score:
      no_aug:
        aug_times: 1
    MMSE_Task_Score:
      no_aug:
        aug_times: 1
  test:
    Gaze_posi:
      no_aug:
        aug_times: 1
    EEG:
      no_aug:
        aug_times: 1
    Task_id:
      no_aug:
        aug_times: 1
    Task_embed:
      no_aug:
        aug_times: 1
    MoCA:
      no_aug:
        aug_times: 1
    MMSE:
      no_aug:
        aug_times: 1
    MoCA_Task_Score:
      no_aug:
        aug_times: 1
    MMSE_Task_Score:
      no_aug:
        aug_times: 1

norm_params:
  EEG:
    sequence:
      max_value: 8087.9805
      mean_value: -0.0003434395
      min_value: -7018.4287
      norm_type: norm_by_subject_task
      std_value: 20.800686
  # Forehead_EEG:
  #   sequence:
  #     max_value: 
  #     mean_value: 
  #     min_value: 
  #     norm_type: norm_by_mean_std
  #     std_value: 
  EOG:
    sequence:
      max_value: 1965.036519799067
      mean_value: -0.0045129696270988975
      min_value: -1584.1758942682995
      norm_type: norm_by_mean_std
      std_value: 14.824471300284605
  Gaze_posi:
    sequence:
      max_value: 3200.46688992919
      mean_value: 972.4825660968037
      min_value: -409.99182789123677
      norm_type: norm_by_mean_std
      std_value: 393.044501894086
  MMSE:
    value:
      max_value: 30.0
      mean_value: 23.033305227655987
      min_value: 0.0
      norm_type: norm_by_min_max
      std_value: 5.717059718000392
  MoCA:
    value:
      max_value: 28.0
      mean_value: 17.8941496951615
      min_value: 0.0
      norm_type: norm_by_min_max
      std_value: 6.793486787029787
  MoCA_Task_Score:
    value:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  MMSE_Task_Score:
    value:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  Task_id:
    value:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  Task_embed:
    last_token:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  Task_score:
    value:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~
  STFT:
    sequence:
      max_value: 42849.39025707162
      mean_value: 2.7748861861441707
      min_value: 7.812917225790438e-15
      norm_type: norm_by_mean_std
      std_value: 34.63873977878058
  PCA:
    sequence:
      max_value: 7946591653.57875
      mean_value: 2.6594581542754934e-07
      min_value: -25072280535.421627
      norm_type: norm_by_mean_std
      std_value: 918031031.5517336
  Raw_feat:
    sequence:
      max_value: ~
      mean_value: ~
      min_value: ~
      norm_type: no_norm
      std_value: ~

num_workers: 2
persistent_workers: True
prefetch_factor: 2


model:
  name: Joint_CLS_REG_Model
  cls_model_name: EyetrackingModel
  # reg_model_name: Regression_MLP
  reg_model_name: Regression_Transformer_TaskScore # Regression_Transformer
  input_channels: 2
  emb_size: 40 ### for the cls model
  num_classes: 9
  load_pretrained_backbone: False
  freeze_backbone: False
  cls_n_dim: 60
  cls_depth: 12
  backbone_weight_path: ~
  ### mask_ratio 0.75: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_18_00_34/best_mae_ratio_model.pth
  ### mask_ratio 0.5: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_17_58_09/best_mae_ratio_model.pth
  ### mask_ratio 0.25: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_18_00_55/best_mae_ratio_model.pth
  n_dim: 60
  reg_depth: 2
  num_reg_dims: 2
  reg_hidden_dims: [1024, 512, 256, 32]
  input_length: 375
  patch_sizes: [25, 16]
  pretrained: ~
  aug_methods: ### same as the data_augs in the regressor cfg file
    features_preprocess:
        method: intra_task_attention ### task attention includes task_preprocessing
        contrast_task:
          - 2
          - 3
          - 6
    train:
      features:
        random_intra_task_sample-random_order_numpy_array:
          aug_times: 100
          feat_len: 256
          sample_ratio: 0.6
          ratio: 1
        mix_up:
          aug_times: 100
      MMSE:
        no_aug:
          aug_times: 100
      MoCA:
        no_aug:
          aug_times: 100
      MMSE_taskscore:
        no_aug:
          aug_times: 100
      MoCA_taskscore: 
        no_aug:
          aug_times: 100
    test:
      features:
        avg_intra_task_sample:
          aug_times: 1
          ratio: 1
      MMSE:
        no_aug:
          aug_times: 1
      MoCA:
        no_aug:
          aug_times: 1
      MMSE_taskscore:
        no_aug:
          aug_times: 1
      MoCA_taskscore:
        no_aug:
          aug_times: 1


Loss:
  name: CrossEntropy
  params:
    alpha: 0
    beta: 0
  
Test_Loss:
  name: CrossEntropy
  params:
    alpha: 0
    beta: 0
    
seed: 43
cpu: ~
cpu_affinity: ~
gpu: 1

batch_size: 64
lr_init: 0.001 # 0.0001
warmup_epochs: 20
epochs: 100
scheduler: cosine
optimizer: Adam

cross_validation: 5-folder
train: True
evaluate: ~
resume: ~ # /data/mmWave_group/EasyCog/models/checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/Cls_Reg_Together/cfg_joint_train_classifier_mask_pretrain_CBraMod_RegMLP.yml/2025_04_14_15_01_36/best_moca_r2_model_testset4.pth

train_stage: vanilla

DA:
  if_use: False
  Adapt_Data_Ratio: 1
  methods: ~

### This is for saving path. 
### You need to make sure you have the permission to write in this path.
save_path: /mnt/glusterfs/home/zhenghang/hqy/EasyCog/models/checkpoints_EyetrackingModel/eye_tracking_our_scheme
train_subject: ~
valid_subject: ~
test_subject: ~

is_split_trials_json_dict: True
logger_file: ~

record: record.txt
save_epoch: 10

### This is for single-task classification
classes: 9
task: classification

### This is for multi-task classification and regression
### If there is multi-task, please use this. The above single-task classification will be ignored.
### classificaton-10, classification-{num_classes} | regression-{num_dims}
### The first item is for classification, the second is for MoCA regression, the third is for MMSE regression
# multi-task: ~ # [classification-10, regression-1, regression-1] 
multi-task: [classification-9] 


### This is for printing and testing frequency
print_freq: 10
test_freq: 1

### This is for mask-autoencoder pretrain
### If there is no mask-autoencoder pretrain, please ignore this.
mask_ratio: 0.25

debug: False

joint_cls_reg_train: True

pic_finetune: False