sliced_data_folder_clean: /mnt/glusterfs/home/zhenghang/hqy/EasyCog/data_v0428/sliced_feat_train/asreog_filter_order3_clean_data_0426
sliced_trials_json_clean: /home/zhenghang/qingyong/EasyCog/data_json_files/proc_compare_json/converted_asreog_filter_order3_clean_data_0426.json

sliced_data_folder_all: /mnt/glusterfs/home/zhenghang/hqy/EasyCog/data_v0428/sliced_feat_train/asreog_filter_order3_all_data
sliced_trials_json_all: /home/zhenghang/qingyong/EasyCog/data_json_files/proc_compare_json/converted_asreog_filter_order3_all_data_0426.json


dataloader: EasyCog_Joint_Training_Dataloader
cog_task: 'video' # 'video' or 'resting' or 'all'

input_type_list:
- Gaze_posi

input_format_dict:
  Gaze_posi:
  - sequence


gt_type_list:
- MoCA
- MMSE
- MoCA_taskscore
- MMSE_taskscore

gt_format_dict:
  MoCA:
  - value
  MMSE:
  - value
  MoCA_taskscore:
  - value
  MMSE_taskscore:
  - value

norm_params:
  EEG:
    sequence:
      max_value: 8087.9805
      mean_value: -0.0003434395
      min_value: -7018.4287
      norm_type: norm_by_mean_std
      std_value: 20.800686
  EOG:
    sequence:
      max_value: 1965.036519799067
      mean_value: -0.0045129696270988975
      min_value: -1584.1758942682995
      norm_type: norm_by_mean_std
      std_value: 14.824471300284605
  Gaze_posi:
    sequence:
      max_value: 3200.46688992919
      mean_value: 972.4825660968037
      min_value: -409.99182789123677
      norm_type: norm_by_mean_std
      std_value: 393.044501894086

  MMSE:
    value:
      max_value: 30.0
      mean_value: 23.033305227655987
      min_value: 0.0
      norm_type: norm_by_min_max
      std_value: 5.717059718000392
  MoCA:
    value:
      max_value: 30.0
      mean_value: 17.8941496951615
      min_value: 0.0
      norm_type: norm_by_min_max
      std_value: 6.793486787029787
  
  MoCA_taskscore:
    value:
      norm_type: no_norm
  MMSE_taskscore:
    value:
      norm_type: no_norm

### mainly work on dataloader
data_aug_methods:
  train:
    EEG:
      no_aug:
        aug_times: 1
    EOG:
      no_aug:
        aug_times: 1
    Gaze_posi:
      no_aug:
        aug_times: 1
    MMSE:
      no_aug:
        aug_times: 1
    MoCA:
      no_aug:
        aug_times: 1
    MMSE_taskscore:
      no_aug:
        aug_times: 1
    MoCA_taskscore:
      no_aug:
        aug_times: 1
        
  test:
    EEG:
      no_aug:
        aug_times: 1
    EOG:
      no_aug:
        aug_times: 1
    Gaze_posi:
      no_aug:
        aug_times: 1
    features:
      avg_intra_task_sample:
        aug_times: 1
        ratio: 1
    MMSE:
      no_aug:
        aug_times: 1
    MoCA:
      no_aug:
        aug_times: 1
    MoCA_taskscore:
      no_aug:
        aug_times: 1
    MMSE_taskscore:
      no_aug:
        aug_times: 1

num_workers: 0
persistent_workers: ~
prefetch_factor: ~

model:
  name: Joint_CLS_REG_Model
  cls_model_name: EyetrackingModel
  # reg_model_name: Regression_MLP
  reg_model_name: Regression_Transformer_TaskScore # Regression_Transformer
  input_channels: 2
  emb_size: 40 ### for the cls model
  num_classes: 9
  load_pretrained_backbone: False
  freeze_backbone: False
  cls_n_dim: 60
  cls_depth: 12
  backbone_weight_path: ~
  ### mask_ratio 0.75: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_18_00_34/best_mae_ratio_model.pth
  ### mask_ratio 0.5: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_17_58_09/best_mae_ratio_model.pth
  ### mask_ratio 0.25: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_18_00_55/best_mae_ratio_model.pth
  n_dim: 200
  reg_depth: 2
  num_reg_dims: 2
  reg_hidden_dims: [1024, 512, 256, 32]
  input_length: 375
  patch_sizes: [25, 16]
  pretrained: ~
  aug_methods: ### same as the data_augs in the regressor cfg file
    features_preprocess:
        method: intra_task_attention ### task attention includes task_preprocessing
        contrast_task:
          - 2
          - 3
          - 6
    train:
      features:
        random_intra_task_sample-random_order_numpy_array:
          aug_times: 100
          feat_len: 256
          sample_ratio: 0.6
          ratio: 1
        mix_up:
          aug_times: 100
      MMSE:
        no_aug:
          aug_times: 100
      MoCA:
        no_aug:
          aug_times: 100
      MMSE_taskscore:
        no_aug:
          aug_times: 100
      MoCA_taskscore: 
        no_aug:
          aug_times: 100
    test:
      features:
        avg_intra_task_sample:
          aug_times: 1
          ratio: 1
      MMSE:
        no_aug:
          aug_times: 1
      MoCA:
        no_aug:
          aug_times: 1
      MMSE_taskscore:
        no_aug:
          aug_times: 1
      MoCA_taskscore:
        no_aug:
          aug_times: 1

# model:
#   name: Joint_CLS_REG_Model_yx
#   cls_model_name: CBraMod_BaseModel
#   reg_model_name: Regression_MLP
#   input_channels: 16
#   emb_size: 40 ### for the cls model
#   num_classes: 10
#   load_pretrained_backbone: True
#   freeze_backbone: False
#   cls_n_dim: 200
#   cls_depth: 12
#   backbone_weight_path: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_17_58_09/best_mae_ratio_model.pth
#   ### mask_ratio 0.75: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_18_00_34/best_mae_ratio_model.pth
#   ### mask_ratio 0.5: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_17_58_09/best_mae_ratio_model.pth
#   ### mask_ratio 0.25: ./checkpoints_CBraMod_Mask_Autoencoder_Pretrain_DL_pipeline/configs/mask_pretrain/cfg_CBraMod_Pretrained_asreog_filter3_clean_data_Mask_Autoencoder_Pretrain.yml/2025_03_28_18_00_55/best_mae_ratio_model.pth
#   n_dim: 200
#   reg_depth: 2
#   reg_hidden_dims: [1024, 512, 256, 32]
#   input_length: 375
#   patch_sizes: [25, 16]
#   pretrained: ~
#   aug_methods: ### same as the data_augs in the regressor cfg file
#     train:
#       features:
#         random_intra_task_sample-random_order_numpy_array:
#           aug_times: 300
#           feat_len: 256
#           sample_ratio: 0.3
#           ratio: 1
#       MMSE:
#         no_aug:
#           aug_times: 300
#       MoCA:
#         no_aug:
#           aug_times: 300
#       MMSE_taskscore:
#         no_aug:
#           aug_times: 300
#       MoCA_taskscore:
#         no_aug:
#           aug_times: 300
#     test:
#       features:
#         avg_intra_task_sample:
#           aug_times: 1
#           ratio: 1
#       MMSE:
#         no_aug:
#           aug_times: 1
#       MoCA:
#         no_aug:
#           aug_times: 1
#       MMSE_taskscore:
#         no_aug:
#           aug_times: 1
#       MoCA_taskscore:
#         no_aug:
#           aug_times: 1

Loss:
  name: reg_L1_Loss_Subscore_Similarity
  params:
    alpha: 1
    beta: 0.1
    gamma: 0.1
    theta: 0
    delta: 0

Test_Loss:
  name: reg_L1_Loss_Subscore_Similarity
  params:
    alpha: 1
    beta: 0.1
    gamma: 0.1
    theta: 0
    delta: 0

# Loss:
#   name: reg_L2_Loss
#   params:
#     alpha: 1


# Test_Loss:
#   name: reg_L2_Loss
#   params:
#     alpha: 1

seed: 43
cpu: ~
cpu_affinity: ~
gpu: 1


batch_size: 4
lr_init: 0.001 # 0.0001
warmup_epochs: 20
epochs: 100
scheduler: cosine
optimizer: Adam
weight_decay: 0.00001


cross_validation: 5-folder
train: True
evaluate: ~
resume: ~


train_stage: cog_regression # direct train wo domain adaptation or self-supervised learning

DA:
  if_use: False
  Adapt_Data_Ratio: 1
  methods: ~



save_path: /mnt/glusterfs/home/zhenghang/hqy/EasyCog/models/checkpoints_EyetrackingModel/eye_tracking_our_scheme
train_subject: ~
valid_subject: ~
test_subject: ~

is_split_trials_json_dict: True
logger_file: ~

record: record.txt
save_epoch: 10


multi-task: ~
task: regression
classes: 10

print_freq: 1
test_freq: 1